import 'package:json_annotation/json_annotation.dart';

part 'car_model.g.dart';

// ─────────────────────────────────────────────────────────────────
// CarModel — the core domain entity.
//
// @JsonSerializable lets build_runner generate fromJson/toJson,
// satisfying the requirement: "JSON → Dart model classes".
//
// Run:  flutter pub run build_runner build --delete-conflicting-outputs
// ─────────────────────────────────────────────────────────────────
@JsonSerializable(fieldRename: FieldRename.snake)
class CarModel {
  const CarModel({
    required this.id,
    required this.make,
    required this.model,
    required this.year,
    required this.price,
    required this.mileage,
    required this.fuelType,
    required this.transmission,
    required this.condition,
    required this.color,
    required this.imageUrl,
    this.description,
    this.rating,
    this.reviewCount,
  });

  final String  id;
  final String  make;
  final String  model;
  final int     year;
  final double  price;
  final int     mileage;
  final String  fuelType;       // 'Gasoline' | 'Electric' | 'Hybrid'
  final String  transmission;
  final String  condition;      // 'New' | 'Used' | 'Certified Pre-Owned'
  final String  color;
  final String  imageUrl;
  final String? description;
  final double? rating;
  final int?    reviewCount;

  // Generated by build_runner
  factory CarModel.fromJson(Map<String, dynamic> json) =>
      _$CarModelFromJson(json);
  Map<String, dynamic> toJson() => _$CarModelToJson(this);

  // ── Convenience getters ───────────────────────────────────────
  String get displayName => '$year $make $model';

  String get formattedPrice {
    final n = price.toStringAsFixed(0);
    return '\$${n.replaceAllMapped(
      RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
          (m) => '${m[1]},',
    )}';
  }

  String get formattedMileage {
    if (condition == 'New') return 'New';
    return '${mileage.toString().replaceAllMapped(
      RegExp(r'(\d{1,3})(?=(\d{3})+(?!\d))'),
          (m) => '${m[1]},',
    )} mi';
  }
}

// ─────────────────────────────────────────────────────────────────
// Seed / placeholder data
// Used during development before the Chopper API is wired up.
// Replace CarsRepository.fetchAll() with a real HTTP call later.
// ─────────────────────────────────────────────────────────────────
const List<CarModel> kSeedCars = [
  CarModel(
    id: '1', make: 'BMW', model: 'M4 Competition',
    year: 2024, price: 89500, mileage: 0,
    fuelType: 'Gasoline', transmission: 'Automatic',
    condition: 'New', color: 'Tanzanite Blue',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80',
    rating: 4.9, reviewCount: 142,
  ),
  CarModel(
    id: '2', make: 'Mercedes-Benz', model: 'AMG GT 63',
    year: 2023, price: 165000, mileage: 5200,
    fuelType: 'Gasoline', transmission: 'Automatic',
    condition: 'Certified Pre-Owned', color: 'Obsidian Black',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&q=80',
    rating: 4.8, reviewCount: 87,
  ),
  CarModel(
    id: '3', make: 'Porsche', model: '911 Carrera S',
    year: 2024, price: 131000, mileage: 0,
    fuelType: 'Gasoline', transmission: 'PDK',
    condition: 'New', color: 'GT Silver',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80',
    rating: 5.0, reviewCount: 213,
  ),
  CarModel(
    id: '4', make: 'Tesla', model: 'Model S Plaid',
    year: 2024, price: 89990, mileage: 0,
    fuelType: 'Electric', transmission: 'Single-Speed',
    condition: 'New', color: 'Deep Blue Metallic',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80',
    rating: 4.7, reviewCount: 395,
  ),
  CarModel(
    id: '5', make: 'Lamborghini', model: 'Huracán Evo',
    year: 2022, price: 248000, mileage: 3100,
    fuelType: 'Gasoline', transmission: '7-Speed DCT',
    condition: 'Used', color: 'Arancio Borealis',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Lamborghini_Hurac%C3%A1n_Evo_Front.jpg',
    rating: 4.9, reviewCount: 61,
  ),
  CarModel(
    id: '6', make: 'Audi', model: 'RS7 Sportback',
    year: 2023, price: 119000, mileage: 11400,
    fuelType: 'Gasoline', transmission: '8-Speed Tiptronic',
    condition: 'Certified Pre-Owned', color: 'Nardo Grey',
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&q=80',
    rating: 4.6, reviewCount: 108,
  ),
  CarModel(
    id: '7', make: 'Ferrari', model: 'Roma',
    year: 2023, price: 222000, mileage: 1800,
    fuelType: 'Gasoline', transmission: '8-Speed DCT',
    condition: 'Used', color: 'Rosso Portofino',
    imageUrl: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=800&q=80',
    rating: 4.9, reviewCount: 44,
  ),
  CarModel(
    id: '8', make: 'Range Rover', model: 'Sport SVR',
    year: 2024, price: 118000, mileage: 0,
    fuelType: 'Gasoline', transmission: 'Automatic',
    condition: 'New', color: 'Santorini Black',
    imageUrl: 'https://images.unsplash.com/photo-1518987048-93e29699e79a?w=800&q=80',
    rating: 4.5, reviewCount: 176,
  ),
];