// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBALTnQ6M0bJKh7UdzI3Ecb4C5tw_Jc9DA',
    appId: '1:62295780076:web:fb5eeaddc15deb28a1d3c9',
    messagingSenderId: '62295780076',
    projectId: 'final-car-fa453',
    authDomain: 'final-car-fa453.firebaseapp.com',
    storageBucket: 'final-car-fa453.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpy6HuJBoSJYsdg_UQ0Q_kPmUzfh1ZnBo',
    appId: '1:62295780076:android:83413981dddc6b5ba1d3c9',
    messagingSenderId: '62295780076',
    projectId: 'final-car-fa453',
    storageBucket: 'final-car-fa453.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSP_exh8ecaTOc_KwNSuaIm8yB1Ap7iag',
    appId: '1:62295780076:ios:5431d70f98b71889a1d3c9',
    messagingSenderId: '62295780076',
    projectId: 'final-car-fa453',
    storageBucket: 'final-car-fa453.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSP_exh8ecaTOc_KwNSuaIm8yB1Ap7iag',
    appId: '1:62295780076:ios:5431d70f98b71889a1d3c9',
    messagingSenderId: '62295780076',
    projectId: 'final-car-fa453',
    storageBucket: 'final-car-fa453.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBALTnQ6M0bJKh7UdzI3Ecb4C5tw_Jc9DA',
    appId: '1:62295780076:web:67bfb5517627cceca1d3c9',
    messagingSenderId: '62295780076',
    projectId: 'final-car-fa453',
    authDomain: 'final-car-fa453.firebaseapp.com',
    storageBucket: 'final-car-fa453.firebasestorage.app',
  );
}
